name: TrickOrTreat
version: '2.5'
main: fr.elias.trickortreatplugin.TrickOrTreatPlugin
api-version: '1.20'
softdepend: [LibsDisguises, LuckPerms, PlaceholderAPI]

commands:
  tt:
    description: TrickOrTreat main command
    usage: /tt <help|pumpkins|horseman|reload>
    aliases: [trickortreat]

permissions:
  trickortreat.*:
    description: All TrickOrTreat permissions
    children:
      trickortreat.horseman: true
      trickortreat.reload: true
      trickortreat.bypass.cooldown: true

  trickortreat.horseman:
    default: op
    description: Use /tt horseman to attempt boss spawn

  trickortreat.reload:
    default: op
    description: Reload all configs & handlers with /tt reload

  trickortreat.bypass.cooldown:
    default: op
    description: Bypass villager/pumpkin cooldowns
